spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myblog?serverTimezone=GMT%2B8
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mail:
      username: 2404240896@qq.com
      password: fzmqvbehniovdhga
      host: smtp.qq.com
      properties:
        mail:
          smtp:
            ssl:
              enable: true
logging:
  level:
    root: info
    com.qiufeng: debug
  file: log/blog-dev.log
http:
  port: 8081
server:
  port: 8888
  ssl:
    key-store: classpath:4474412_www.qfblog.top.pfx
    key-store-password: vG93nROA
    keyStoreType: PKCS12
    enabled: true
preread:
  uploadPath: /usr/local/src/images/